version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to do in the install phase..."
  pre_build:
    commands:
      - chmod +x ec2rl
  build:
    commands:
      - echo "Build started on $(date)"
      - make ${MAKEARGS}
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
    - ec2rl*tgz
    - ec2rl*sha256
    - ec2rl*rpm
