#!/bin/bash

# Copyright 2016-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.

BASEDIR="$(dirname "$(readlink -f "$0")")"

declare -a python_executables=(python2.7 python3)
if which python &> /dev/null; then
    if [ "$(readlink "$(which python 2>/dev/null)")" != "$(readlink "$(which python2.7 2>/dev/null)")" ] \
    && [ "$(readlink "$(which python 2>/dev/null)")" != "$(readlink "$(which python3 2>/dev/null)")" ]; then
        python_executables[2]="$(readlink $(which python))"
    fi
fi

for py_executable in ${python_executables[@]}; do
    if which "$py_executable" &>/dev/null; then
        /usr/bin/env "$py_executable" "$BASEDIR/ec2rl.py" "$@"
        declare -i ret=$?
        if [ "$ret" -eq 0 ]; then
            exit $?
        elif [ "$ret" -ne 201 ]; then
            exit $?
        fi
        # If exit code is 201 then continue on to try other versions of Python
    fi
done
echo -e "Error:\tFailed to find compatible Python environment to run ec2rl!"
