name: Build_rpm
on:
  push: 
    tags:
      - 'v*'

jobs:
  Build_rpm:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Make rpm
          run: make rpm

        - name: Upload rpm
          id: create_release
          uses: actions/create-release@v1
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false
         
