name: Build_rpm
on: [push]
jobs:
  Build_rpm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List directory
        run: ls ${{ github.workspace }}
      - name: make rpm
	working-directory: ${{ github.workspace }}
        run: make rpm
