name: Build_rpm
on: [push]
jobs:
  Build_rpm:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - run: cd ..
- run: pwd 
      - run: ls
      - run: cd ..
- run: pwd 
      - run: ls
      - run: cd ..
- run: pwd 
      - run: ls
      - run: cd ..
- run: pwd 
      - run: ls
      - run: cd ..
      - run: make --makefile="~/work/aws-ec2rescue-linux/Makefile" rpm
